// Liste des provinces de la RDC
export const RDC_PROVINCES = [
  "Kinshasa",
  "Kongo-Central",
  "Haut-Katanga",
  "Nord-Kivu",
  "Sud-Kivu",
  "Kasaï",
  "Kasaï-Central",
  "Kasaï-Oriental",
  "Lomami",
  "Sankuru",
  "Maniema",
  "Tshopo",
  "Bas-Uele",
  "Haut-Uele",
  "Ituri",
  "Équateur",
  "Mongala",
  "Nord-Ubangi",
  "Sud-Ubangi",
  "Tshuapa",
  "Mai-Ndombe",
  "Kwilu",
  "Kwango",
  "Lualaba",
  "Haut-Lomami",
  "Tanganyika",
] ;
